/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
import type { RequestArgs } from './base'
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from './base'

export interface HTTPValidationError {
  detail?: Array<ValidationError>
}
/**
 * Languages
 */

export const Language = {
  English: 'English',
  Spanish: 'Spanish',
  French: 'French',
  German: 'German',
} as const

export type Language = (typeof Language)[keyof typeof Language]

export interface PaginatedResponseTextOut {
  items: Array<TextOut>
  pagination: PaginationInfoOut
}
/**
 * Pydantic model representing pagination information
 */
export interface PaginationInfoOut {
  page: number
  page_size: number
  total_items: number
  total_pages: number
}
/**
 * Pydantic model representing the input data for creating a text
 */
export interface TextIn {
  content: string
  language: Language
}

/**
 * Pydantic model representing the output data for a text
 */
export interface TextOut {
  id: string
  content: string
  language: Language
}

export interface ValidationError {
  loc: Array<ValidationErrorLocInner>
  msg: string
  type: string
}
export interface ValidationErrorLocInner {}

/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * General health check endpoint
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheck: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/health`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
  return {
    /**
     * General health check endpoint
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async healthCheck(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.healthCheck(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['HealthApi.healthCheck']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = HealthApiFp(configuration)
  return {
    /**
     * General health check endpoint
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp
        .healthCheck(options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
  /**
   * General health check endpoint
   * @summary Health
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public healthCheck(options?: RawAxiosRequestConfig) {
    return HealthApiFp(this.configuration)
      .healthCheck(options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * TextsApi - axios parameter creator
 */
export const TextsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Endpoint for POST /api/texts to create a new text
     * @summary Create New Text Endpoint
     * @param {TextIn} textIn
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewText: async (
      textIn: TextIn,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'textIn' is not null or undefined
      assertParamExists('createNewText', 'textIn', textIn)
      const localVarPath = `/api/texts`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        textIn,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Endpoint for POST /api/texts to create a new text
     * @summary Create New Text Endpoint
     * @param {TextIn} textIn
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewText_1: async (
      textIn: TextIn,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'textIn' is not null or undefined
      assertParamExists('createNewText_1', 'textIn', textIn)
      const localVarPath = `/api/texts`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        textIn,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
     * @summary Get Text By Id
     * @param {string} textId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTextById: async (
      textId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'textId' is not null or undefined
      assertParamExists('getTextById', 'textId', textId)
      const localVarPath = `/api/texts/{text_id}`.replace(
        `{${'text_id'}}`,
        encodeURIComponent(String(textId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
     * @summary Get Text By Id
     * @param {string} textId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTextById_2: async (
      textId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'textId' is not null or undefined
      assertParamExists('getTextById_2', 'textId', textId)
      const localVarPath = `/api/texts/{text_id}`.replace(
        `{${'text_id'}}`,
        encodeURIComponent(String(textId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Endpoint for GET /api/texts to list all texts
     * @summary Get Texts
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTexts: async (
      page?: number,
      pageSize?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/texts`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (pageSize !== undefined) {
        localVarQueryParameter['page_size'] = pageSize
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Endpoint for GET /api/texts to list all texts
     * @summary Get Texts
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTexts_3: async (
      page?: number,
      pageSize?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/texts`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (pageSize !== undefined) {
        localVarQueryParameter['page_size'] = pageSize
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * TextsApi - functional programming interface
 */
export const TextsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TextsApiAxiosParamCreator(configuration)
  return {
    /**
     * Endpoint for POST /api/texts to create a new text
     * @summary Create New Text Endpoint
     * @param {TextIn} textIn
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createNewText(
      textIn: TextIn,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextOut>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createNewText(
        textIn,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TextsApi.createNewText']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Endpoint for POST /api/texts to create a new text
     * @summary Create New Text Endpoint
     * @param {TextIn} textIn
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createNewText_1(
      textIn: TextIn,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextOut>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createNewText_1(
        textIn,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TextsApi.createNewText_1']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
     * @summary Get Text By Id
     * @param {string} textId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTextById(
      textId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextOut>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTextById(
        textId,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TextsApi.getTextById']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
     * @summary Get Text By Id
     * @param {string} textId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTextById_2(
      textId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextOut>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTextById_2(
        textId,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TextsApi.getTextById_2']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Endpoint for GET /api/texts to list all texts
     * @summary Get Texts
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTexts(
      page?: number,
      pageSize?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedResponseTextOut>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTexts(
        page,
        pageSize,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TextsApi.getTexts']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Endpoint for GET /api/texts to list all texts
     * @summary Get Texts
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTexts_3(
      page?: number,
      pageSize?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedResponseTextOut>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTexts_3(
        page,
        pageSize,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TextsApi.getTexts_3']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * TextsApi - factory interface
 */
export const TextsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TextsApiFp(configuration)
  return {
    /**
     * Endpoint for POST /api/texts to create a new text
     * @summary Create New Text Endpoint
     * @param {TextIn} textIn
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewText(
      textIn: TextIn,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TextOut> {
      return localVarFp
        .createNewText(textIn, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Endpoint for POST /api/texts to create a new text
     * @summary Create New Text Endpoint
     * @param {TextIn} textIn
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewText_1(
      textIn: TextIn,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TextOut> {
      return localVarFp
        .createNewText_1(textIn, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
     * @summary Get Text By Id
     * @param {string} textId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTextById(
      textId: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TextOut> {
      return localVarFp
        .getTextById(textId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
     * @summary Get Text By Id
     * @param {string} textId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTextById_2(
      textId: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TextOut> {
      return localVarFp
        .getTextById_2(textId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Endpoint for GET /api/texts to list all texts
     * @summary Get Texts
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTexts(
      page?: number,
      pageSize?: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedResponseTextOut> {
      return localVarFp
        .getTexts(page, pageSize, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Endpoint for GET /api/texts to list all texts
     * @summary Get Texts
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTexts_3(
      page?: number,
      pageSize?: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedResponseTextOut> {
      return localVarFp
        .getTexts_3(page, pageSize, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * TextsApi - object-oriented interface
 */
export class TextsApi extends BaseAPI {
  /**
   * Endpoint for POST /api/texts to create a new text
   * @summary Create New Text Endpoint
   * @param {TextIn} textIn
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createNewText(textIn: TextIn, options?: RawAxiosRequestConfig) {
    return TextsApiFp(this.configuration)
      .createNewText(textIn, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Endpoint for POST /api/texts to create a new text
   * @summary Create New Text Endpoint
   * @param {TextIn} textIn
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createNewText_1(textIn: TextIn, options?: RawAxiosRequestConfig) {
    return TextsApiFp(this.configuration)
      .createNewText_1(textIn, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
   * @summary Get Text By Id
   * @param {string} textId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTextById(textId: string, options?: RawAxiosRequestConfig) {
    return TextsApiFp(this.configuration)
      .getTextById(textId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Endpoint for GET /api/texts/{text_id} to retrieve a text by its ID
   * @summary Get Text By Id
   * @param {string} textId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTextById_2(textId: string, options?: RawAxiosRequestConfig) {
    return TextsApiFp(this.configuration)
      .getTextById_2(textId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Endpoint for GET /api/texts to list all texts
   * @summary Get Texts
   * @param {number} [page]
   * @param {number} [pageSize]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTexts(
    page?: number,
    pageSize?: number,
    options?: RawAxiosRequestConfig,
  ) {
    return TextsApiFp(this.configuration)
      .getTexts(page, pageSize, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Endpoint for GET /api/texts to list all texts
   * @summary Get Texts
   * @param {number} [page]
   * @param {number} [pageSize]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTexts_3(
    page?: number,
    pageSize?: number,
    options?: RawAxiosRequestConfig,
  ) {
    return TextsApiFp(this.configuration)
      .getTexts_3(page, pageSize, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
