"""initialize tables

Revision ID: 9241a2ea0ef7
Revises: 
Create Date: 2025-11-29 17:14:40.780345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9241a2ea0ef7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "texts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_texts_content"), "texts", ["content"], unique=False)
    op.create_index(op.f("ix_texts_language"), "texts", ["language"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_texts_language"), table_name="texts")
    op.drop_index(op.f("ix_texts_content"), table_name="texts")
    op.drop_table("texts")
    # ### end Alembic commands ###
