/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextsIndexRouteImport } from './routes/texts/index'
import { Route as TextsTextIdRouteImport } from './routes/texts/$textId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextsIndexRoute = TextsIndexRouteImport.update({
  id: '/texts/',
  path: '/texts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextsTextIdRoute = TextsTextIdRouteImport.update({
  id: '/texts/$textId',
  path: '/texts/$textId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/texts/$textId': typeof TextsTextIdRoute
  '/texts': typeof TextsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/texts/$textId': typeof TextsTextIdRoute
  '/texts': typeof TextsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/texts/$textId': typeof TextsTextIdRoute
  '/texts/': typeof TextsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/texts/$textId' | '/texts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/texts/$textId' | '/texts'
  id: '__root__' | '/' | '/texts/$textId' | '/texts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextsTextIdRoute: typeof TextsTextIdRoute
  TextsIndexRoute: typeof TextsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texts/': {
      id: '/texts/'
      path: '/texts'
      fullPath: '/texts'
      preLoaderRoute: typeof TextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texts/$textId': {
      id: '/texts/$textId'
      path: '/texts/$textId'
      fullPath: '/texts/$textId'
      preLoaderRoute: typeof TextsTextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextsTextIdRoute: TextsTextIdRoute,
  TextsIndexRoute: TextsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
